### PR TITLE
allow conversations to be restored from disk

### PR DESCRIPTION
**Pull request by martelletto**
allow conversations to be saved to disk with /save, and later restored
with /restore. restore saved conversations automatically when
connecting to the server.

### CODE REVIEW

**Comment by martelletto** [comment]
this addresses https://github.com/companyzero/zkc/issues/19.

**Comment by jcvernaleo** [comment]
@martelletto is travis being weird here?  I totally don't see the failure it is complaining about (and I'm very excited about this PR, it is something I've wanted for a while).

**Comment by martelletto** [comment]
Hi @jcvernaleo, thanks for pointing it out! I had missed the Travis warning. It was a problem with gofmt. Hopefully Travis won't complain now.

**Comment by marcopeereboom** [comment]
While I like seeing this I would like to debate refactoring the code before we add more features.  We really need to separate the layers before adding more tangles.

**Comment by jcvernaleo** [comment]
So I think this is contained enough and useful enough that it would be worth merging it and then discussing the overall refactor.

Is there already an issue to discuss the refactor or do we need to open one?

**Comment by martelletto** [comment]
@jcvernaleo, I believe we need to open one.

**Pull request merged**
