### PR TITLE
Do not make tar.gz for windows

### LINKED ISSUE #22: Release script should not make .tar.gz for windows since it has zips

### PR DESCRIPTION
**Pull request by jcvernaleo**
Closes #22

### CODE REVIEW

**Comment by marcopeereboom** [comment]
image

**Comment by jcvernaleo** [comment]
Because people complained.  It doesn't matter to me really since I don't expect to use this on windows.

**Comment by marcopeereboom** [comment]
I'll take a tar.gz over any zip.  Always.

A) don't trust a zip to not do weird things (sec or otherwise) on windows.
B) I run windows like a crippled UNIX machine with mingw.

I don't see the harm in catering to both windows and UNIX users.

Anyone else have strong feelings about this?

**Comment by jrick** [comment]
i'm ok with both.

**Pull request merged**
