### PR TITLE
Make Mode a type instead of using uint32

### PR DESCRIPTION
**Pull request by marcopeereboom**
requested by @dajohi and @jrick

### CODE REVIEW

**Comment by jrick** [comment]
Don't think this is actually a protocol change.  The messages on the wire never changed did they?

**Comment by marcopeereboom** [comment]
It wouldn't but my OCD says it is.

**Comment by dajohi** [comment]
don't bump the protocol version.  no change.

**Comment by marcopeereboom** [comment]
@martelletto please sneak this in during the next proto bump.

**Pull request merged**
